from PySide2.QtGui import *
from PySide2.QtWebEngineWidgets import QWebEnginePage
from PySide2.QtWidgets import *
from PySide2 import QtGui as QtGui, QtWidgets as QtWidgets

# Note: QWebFrame Has Been Merged into QWebEnginePage
# https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html#qwebframe-has-been-merged-into-qwebenginepage

def sessionWindow() -> QMainWindow | None: ...
def sessionGLView() -> QOpenGLWidget | None: ...
def sessionTopToolBar() -> QToolBar | None: ...
def sessionBottomToolBar() -> QToolBar | None: ...
def javascriptExport(webFrame: QWebEnginePage) -> None: ...
