from typing import Sequence

from rvtypes import Mode, Event, State


def modeStatus(mode: Mode) -> bool: ...
def modeDrawOnEmpty(mode: Mode) -> bool: ...
def modeDrawOnPresentation(mode: Mode) -> bool: ...
def modeName(mode: Mode) -> str: ...
def modeActive(mode: Mode) -> bool: ...
def modeActivate(mode: Mode) -> None: ...
def modeDeactivate(mode: Mode) -> None: ...
def modeRender(mode: Mode, event: Event) -> None: ...
def remotePyEval(event: Event) -> None: ...
def remotePyExec(event: Event) -> None: ...
def globalBindList(bindings: Sequence[tuple]) -> None: ...
def defineDefaultBindings() -> None: ...
def newStateObject() -> State: ...
